# Generated by Django 4.0.2 on 2022-04-16 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_socket_alter_oilchange_options_bike_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='caseNo',
            field=models.CharField(default='na', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='headNo',
            field=models.CharField(default='na', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='vin',
            field=models.CharField(default='na', max_length=30),
            preserve_default=False,
        ),
    ]
