# Generated by Django 4.0.2 on 2022-04-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_bike_caseno_bike_headno_bike_owner_bike_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
