# Generated by Django 4.0.2 on 2022-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bike_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maintenance', models.TextField(max_length=300)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bike')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='OilChange',
        ),
    ]
